# -*- coding: utf-8 -*-
"""LLM_TOKENIZAION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pg9i9UDDc8SsIFgPSw8LeBrg3yDsd2WS

1.Creatibg tokens
"""

with open ("/the-verdict.txt","r", encoding="utf-8") as f :
  raw_text = f.read()
  print ("total no of characters :", len(raw_text))
  print(raw_text[:99])

"""testing for the re lib"""

import re
text = "hello my. name, is krushna "
results = re.split(r'([,.]|\s)', text )
print(results)

"""white space still counted as toens or items to remove them"""

results = [item for item in results if item.strip()]
print(results)

text = "hellp 'my < name > is  and ; yes : it \ is| my / real ? name , < . "
results = re.split(r'([<>/?.\'"()|\;:]|--|\s)', text)
results = [item.strip() for item in results if item.strip()]
print (results  )

preprocessed   = re.split(r'([<>/?.\'"()|\;:]|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print (preprocessed)
print (len(raw_text))
print(preprocessed[:30])

"""*token ids*"""

all_words = sorted(set(preprocessed))
print(all_words)
print(len(all_words))

vocab = {token: integer for  integer,token in enumerate(all_words)}
print (vocab)

for i , item in enumerate(vocab.items()):
  print(item)
  if i >= 50 :
    break

import re

class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i: s for s, i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([<>/?.\'"()|\;:]|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([<>/?.\'"()|\;:])', r'\1', text)
        return text