# -*- coding: utf-8 -*-
"""LLM_TOKENIZAION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pg9i9UDDc8SsIFgPSw8LeBrg3yDsd2WS

1.Creatibg tokens
"""

with open ("/the-verdict.txt","r", encoding="utf-8") as f :
  raw_text = f.read()
  print ("total no of characters :", len(raw_text))
  print(raw_text[:99])

"""testing for the re lib"""

import re
text = "hello my. name, is krushna "
results = re.split(r'([,.]|\s)', text )
print(results)

"""white space still counted as toens or items to remove them"""

results = [item for item in results if item.strip()]
print(results)

text = "hellp 'my < name > is  and ; yes : it \ is| my / real ? name , < . "
results = re.split(r'([<>/?.\'"()|\;:]|--|\s)', text)
results = [item.strip() for item in results if item.strip()]
print (results  )

preprocessed   = re.split(r'([<>/?.\'"()|\;:]|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print (preprocessed)
print (len(raw_text))
print(preprocessed[:30])

"""*token ids*"""

all_words = sorted(set(preprocessed))
print(all_words)
print(len(all_words))

vocab = {token: integer for  integer,token in enumerate(all_words)}
print (vocab)

for i , item in enumerate(vocab.items()):
  print(item)
  if i >= 50 :
    break

import re

class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i: s for s, i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([<>/?.\'"()|\;:]|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([<>/?.\'"()|\;:])', r'\1', text)
        return text

tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know,"
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)
tokenizer.decode(ids)
text = "Hello, do you like tea?"
print(tokenizer.encode(text))


all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}


  len(vocab.items())

for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

tokenizer.encode(text)

tokenizer.decode(tokenizer.encode(text))

